/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author ramir
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ClasesFormDialog extends JDialog {
    private JTextField txtNombre;
    private JComboBox<String> cmbEntrenador;
    private JTextField txtHorario;
    private JButton btnSave;

    public ClasesFormDialog(Frame owner) {
        super(owner, "Añadir Clase", true);
        setSize(300, 200);
        setLayout(new GridLayout(4, 2, 10, 10));
        setLocationRelativeTo(owner);

        txtNombre = new JTextField(20);
        cmbEntrenador = new JComboBox<>(new String[] {"Juan Pérez", "Ana Gómez"}); // Reemplazar con datos reales
        txtHorario = new JTextField(20);
        btnSave = new JButton("Guardar");

        add(new JLabel("Nombre:"));
        add(txtNombre);
        add(new JLabel("Entrenador:"));
        add(cmbEntrenador);
        add(new JLabel("Horario:"));
        add(txtHorario);
        add(new JLabel(""));
        add(btnSave);

        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String nombre = txtNombre.getText();
                String entrenador = (String) cmbEntrenador.getSelectedItem();
                String horario = txtHorario.getText();

                // Lógica para guardar en la base de datos usando JDBC
                // Por ejemplo:
                // ClaseDAO.addClase(new Clase(nombre, entrenador, horario));

                JOptionPane.showMessageDialog(null, "Clase guardada exitosamente!");
                dispose();
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
