/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author ramir
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class EntrenadoresPanel extends JPanel {
    private JTextField txtSearch;
    private JButton btnSearch, btnAddEntrenador;
    private JTable table;
    private JScrollPane scrollPane;

    public EntrenadoresPanel() {
        setLayout(new BorderLayout());

        JPanel topPanel = new JPanel();
        txtSearch = new JTextField(20);
        btnSearch = new JButton("Buscar");
        btnAddEntrenador = new JButton("Añadir Entrenador");

        topPanel.add(new JLabel("Buscar:"));
        topPanel.add(txtSearch);
        topPanel.add(btnSearch);
        topPanel.add(btnAddEntrenador);

        add(topPanel, BorderLayout.NORTH);

        // Inicializar tabla vacía
        table = new JTable(new Object[0][0], new String[]{"ID", "Nombre", "Apellido", "Especialidad"});
        scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Action listeners
        btnSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String searchTerm = txtSearch.getText();
                // Lógica para buscar en la base de datos
                // List<Entrenador> entrenadores = EntrenadorDAO.searchEntrenadores(searchTerm);

                // Para prueba, reemplazar con datos reales
                Object[][] data = {
                    {1, "Juan", "Pérez", "Yoga"},
                    {2, "Ana", "Gómez", "Pilates"}
                    // Agregar más datos según búsqueda
                };
                table.setModel(new javax.swing.table.DefaultTableModel(
                        data,
                        new String[]{"ID", "Nombre", "Apellido", "Especialidad"}
                ));
            }
        });

        btnAddEntrenador.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new EntrenadoresFormDialog(null).setVisible(true);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
