/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author ramir
 */
import Data.EntrenadorData;
import Entidades.Entrenador;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class EntrenadoresFormDialog extends JDialog {

    private JTextField txtDni;
    private JTextField txtNombre;
    private JTextField txtApellido;
    private JTextField txtEspecialidad;
    private JCheckBox chkEstado;
    private JButton btnSave;

    public EntrenadoresFormDialog(Frame owner) {
        super(owner, "Añadir Entrenador", true);
        setSize(300, 300);
        setLayout(new GridLayout(6, 2, 10, 10));
        setLocationRelativeTo(owner);

        Color backgroundColor = Color.WHITE;
        Color textColor = Color.BLACK; // Negro para el texto
        Color buttonBackgroundColor = new Color(51, 255, 51); // Steel Blue
        Color buttonTextColor = Color.BLACK;

        txtDni = new JTextField(20);
        txtDni.setBackground(backgroundColor);
        txtDni.setForeground(textColor);

        txtNombre = new JTextField(20);
        txtNombre.setBackground(backgroundColor);
        txtNombre.setForeground(textColor);

        txtApellido = new JTextField(20);
        txtApellido.setBackground(backgroundColor);
        txtApellido.setForeground(textColor);

        txtEspecialidad = new JTextField(20);
        txtEspecialidad.setBackground(backgroundColor);
        txtEspecialidad.setForeground(textColor);
        
         chkEstado = new JCheckBox("Activo");

        // Configurar botón
        btnSave = new JButton("Guardar");
        btnSave.setBackground(buttonBackgroundColor);
        btnSave.setForeground(buttonTextColor);

        add(new JLabel("Dni:"));
        add(txtDni);
        add(new JLabel("Nombre:"));
        add(txtNombre);
        add(new JLabel("Apellido:"));
        add(txtApellido);
        add(new JLabel("Especialidad:"));
        add(txtEspecialidad);
        add(new JLabel("Estado:"));
        add(chkEstado);
        add(new JLabel(""));
        add(btnSave);

        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                try {
                logicaGuardadoDeEntrenador();      
                dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al guardar el Entrenador: " + ex.getMessage());
                }
                
            }
        });
        
    }
    
      // Aquí va la lógica para guardar el socio en la base de datos
    private void logicaGuardadoDeEntrenador() {
        
        //Revisa que no queden campos sin completar o mal completados.
          if (txtDni.getText().isBlank() || txtNombre.getText().isBlank() || txtApellido.getText().isBlank()
                || txtEspecialidad.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos antes de agregar un Entrenador.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
    }
          
        String dni = txtDni.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String especialidad = txtEspecialidad.getText();
        boolean estado = chkEstado.isSelected();

        Entrenador entrenador = new Entrenador(0, dni, nombre, apellido, especialidad, estado);
        EntrenadorData ed = new EntrenadorData();

        ed.agregarEntrenador(entrenador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
