/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author rodrigo
 */
public class GymApp extends javax.swing.JFrame {

    /**
     * Creates new form GymApp
     */
    public GymApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMGestionSocios = new javax.swing.JMenu();
        jM_Item_AddSocio = new javax.swing.JMenuItem();
        jM_Item_ListSocios = new javax.swing.JMenuItem();
        jM_Item_BuscarSocio = new javax.swing.JMenuItem();
        jMGestionMembresias = new javax.swing.JMenu();
        jM_Item_NuevaMembresia = new javax.swing.JMenuItem();
        jM_Item_HistorialMembresia = new javax.swing.JMenuItem();
        jM_Item_GestionarMembresia = new javax.swing.JMenuItem();
        jMGestionClases = new javax.swing.JMenu();
        jM_Item_AddClase = new javax.swing.JMenuItem();
        jM_Item_ListClases = new javax.swing.JMenuItem();
        jM_Item_BuscarClase = new javax.swing.JMenuItem();
        jM_Item_InscribirSocioAClase = new javax.swing.JMenuItem();
        jMGestionEntrenadores = new javax.swing.JMenu();
        jM_Item_NewEntrenador = new javax.swing.JMenuItem();
        jM_Item_ListEntrenadores = new javax.swing.JMenuItem();
        jM_Item_BuscarEntrenador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jMGestionSocios.setText("Gestion De Socios");

        jM_Item_AddSocio.setText("Añadir Nuevo Socio");
        jM_Item_AddSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Item_AddSocioActionPerformed(evt);
            }
        });
        jMGestionSocios.add(jM_Item_AddSocio);

        jM_Item_ListSocios.setText("Ver lista de Socios");
        jM_Item_ListSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Item_ListSociosActionPerformed(evt);
            }
        });
        jMGestionSocios.add(jM_Item_ListSocios);

        jM_Item_BuscarSocio.setText("Buscar Socio");
        jMGestionSocios.add(jM_Item_BuscarSocio);

        jMenuBar1.add(jMGestionSocios);

        jMGestionMembresias.setText("Gestion De Membresias");

        jM_Item_NuevaMembresia.setText("Registrar Nueva Membresia");
        jMGestionMembresias.add(jM_Item_NuevaMembresia);

        jM_Item_HistorialMembresia.setText("Ver Mi Historial De Membresias");
        jMGestionMembresias.add(jM_Item_HistorialMembresia);

        jM_Item_GestionarMembresia.setText("Gestionar Membresia");
        jMGestionMembresias.add(jM_Item_GestionarMembresia);

        jMenuBar1.add(jMGestionMembresias);

        jMGestionClases.setText("Gestion De Clases");

        jM_Item_AddClase.setText("Añadir Nueva Clase");
        jMGestionClases.add(jM_Item_AddClase);

        jM_Item_ListClases.setText("Ver Lista De Clases");
        jMGestionClases.add(jM_Item_ListClases);

        jM_Item_BuscarClase.setText("Buscar Clase");
        jMGestionClases.add(jM_Item_BuscarClase);

        jM_Item_InscribirSocioAClase.setText("Inscribir Socio a Clase");
        jM_Item_InscribirSocioAClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Item_InscribirSocioAClaseActionPerformed(evt);
            }
        });
        jMGestionClases.add(jM_Item_InscribirSocioAClase);

        jMenuBar1.add(jMGestionClases);

        jMGestionEntrenadores.setText("Gestion De Entrenadores");

        jM_Item_NewEntrenador.setText("Añadir Nuevo Entrenador");
        jMGestionEntrenadores.add(jM_Item_NewEntrenador);

        jM_Item_ListEntrenadores.setText("Ver Lista de Entrenadores");
        jM_Item_ListEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Item_ListEntrenadoresActionPerformed(evt);
            }
        });
        jMGestionEntrenadores.add(jM_Item_ListEntrenadores);

        jM_Item_BuscarEntrenador.setText("Buscar Entrenador");
        jMGestionEntrenadores.add(jM_Item_BuscarEntrenador);

        jMenuBar1.add(jMGestionEntrenadores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_Item_AddSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Item_AddSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_Item_AddSocioActionPerformed

    private void jM_Item_ListEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Item_ListEntrenadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_Item_ListEntrenadoresActionPerformed

    private void jM_Item_InscribirSocioAClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Item_InscribirSocioAClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_Item_InscribirSocioAClaseActionPerformed

    private void jM_Item_ListSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Item_ListSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_Item_ListSociosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMGestionClases;
    private javax.swing.JMenu jMGestionEntrenadores;
    private javax.swing.JMenu jMGestionMembresias;
    private javax.swing.JMenu jMGestionSocios;
    private javax.swing.JMenuItem jM_Item_AddClase;
    private javax.swing.JMenuItem jM_Item_AddSocio;
    private javax.swing.JMenuItem jM_Item_BuscarClase;
    private javax.swing.JMenuItem jM_Item_BuscarEntrenador;
    private javax.swing.JMenuItem jM_Item_BuscarSocio;
    private javax.swing.JMenuItem jM_Item_GestionarMembresia;
    private javax.swing.JMenuItem jM_Item_HistorialMembresia;
    private javax.swing.JMenuItem jM_Item_InscribirSocioAClase;
    private javax.swing.JMenuItem jM_Item_ListClases;
    private javax.swing.JMenuItem jM_Item_ListEntrenadores;
    private javax.swing.JMenuItem jM_Item_ListSocios;
    private javax.swing.JMenuItem jM_Item_NewEntrenador;
    private javax.swing.JMenuItem jM_Item_NuevaMembresia;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
