/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author ramir
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class InscribirSocioDialog extends JDialog {
    private JComboBox<String> cmbSocio;
    private JComboBox<String> cmbClase;
    private JButton btnSave;

    public InscribirSocioDialog(Frame owner) {
        super(owner, "Inscribir Socio en Clase", true);
        setSize(300, 150);
        setLayout(new GridLayout(3, 2, 10, 10));
        setLocationRelativeTo(owner);

        cmbSocio = new JComboBox<>(new String[] {"Socio 1asdasdasasd", "Socio 2"}); // Reemplazar con datos reales
        cmbClase = new JComboBox<>(new String[] {"Yoga", "Pilates"}); // Reemplazar con datos reales
        btnSave = new JButton("Guardar");

        add(new JLabel("Socio:"));
        add(cmbSocio);
        add(new JLabel("Clase:"));
        add(cmbClase);
        add(new JLabel(""));
        add(btnSave);

        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String socio = (String) cmbSocio.getSelectedItem();
                String clase = (String) cmbClase.getSelectedItem();

                // Lógica para inscribir en la base de datos usando JDBC
                // Por ejemplo:
                // InscripcionDAO.inscribirSocioEnClase(socio, clase);

                JOptionPane.showMessageDialog(null, "Socio inscrito en clase exitosamente!");
                dispose();
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
