package Vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

public class MembresiaFormDialog extends JDialog {
    private JTextField socioField, cantidadPasesField, duracionField;
    private JButton saveButton, cancelButton;
    private DefaultTableModel tableModel;

    public MembresiaFormDialog(Frame parent, DefaultTableModel tableModel) {
        super(parent, "Añadir Membresía", true);
        this.tableModel = tableModel;
        setLayout(new GridLayout(5, 2));

        socioField = new JTextField();
        cantidadPasesField = new JTextField();
        duracionField = new JTextField();

        saveButton = new JButton("Guardar");
        cancelButton = new JButton("Cancelar");

        add(new JLabel("Socio:"));
        add(socioField);
        add(new JLabel("Cantidad de Pases:"));
        add(cantidadPasesField);
        add(new JLabel("Duración (meses):"));
        add(duracionField);
        add(saveButton);
        add(cancelButton);

        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String socio = socioField.getText().trim();
                String cantidadPases = cantidadPasesField.getText().trim();
                String duracion = duracionField.getText().trim();

                if (socio.isEmpty() || cantidadPases.isEmpty() || duracion.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
                    return;
                }

                // Aquí se puede agregar la lógica para guardar la membresía en la base de datos

                // Añadir membresía a la tabla
                tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, socio, cantidadPases, duracion, new Date(), new Date()});

                dispose();
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        setSize(300, 200);
        setLocationRelativeTo(parent);
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
