/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Vistas.MembresiaFormDialog;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ramir
 */
public class MembresiasPanel extends JPanel {
    private JTable membresiasTable;
    private JButton addButton, deleteButton, renewButton, searchButton;
    private JTextField searchField;
    private DefaultTableModel tableModel;

    public MembresiasPanel() {
        setLayout(new BorderLayout());

        // Panel superior con el campo de búsqueda y botones
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout());

        searchField = new JTextField(20);
        searchButton = new JButton("Buscar");
        addButton = new JButton("Añadir Membresía");
        deleteButton = new JButton("Cancelar Membresía");
        renewButton = new JButton("Renovar Membresía");

        topPanel.add(new JLabel("Buscar Socio:"));
        topPanel.add(searchField);
        topPanel.add(searchButton);
        topPanel.add(addButton);
        topPanel.add(deleteButton);
        topPanel.add(renewButton);

        add(topPanel, BorderLayout.NORTH);

        // Modelo de la tabla de membresías
        tableModel = new DefaultTableModel(new Object[]{"ID", "Socio", "Cantidad de Pases", "Duración (meses)", "Fecha de Inicio", "Fecha de Fin"}, 0);
        membresiasTable = new JTable(tableModel);
        add(new JScrollPane(membresiasTable), BorderLayout.CENTER);

        // Eventos
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new MembresiaFormDialog(null, tableModel);
            }
        });

        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = membresiasTable.getSelectedRow();
                if (selectedRow != -1) {
                    tableModel.removeRow(selectedRow);
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione una membresía para cancelar.");
                }
            }
        });

        renewButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = membresiasTable.getSelectedRow();
                if (selectedRow != -1) {
                    // Aquí se puede agregar la lógica para renovar la membresía
                    JOptionPane.showMessageDialog(null, "Membresía renovada.");
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione una membresía para renovar.");
                }
            }
        });

        searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String searchText = searchField.getText().trim().toLowerCase();
                // Aquí se puede agregar la lógica para filtrar las membresías por socio
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
