package Vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import Data.MembresiaData;
import Data.SocioData;
import Entidades.Membresia;
import Entidades.Socio;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class MembresiaFormDialog extends JDialog {
    private JComboBox<Socio> cmbSocio;
    private JTextField txtCantidadPases;
    private JTextField txtFechaInicio;
    private JTextField txtFechaFin;
    private JTextField txtCosto;
    private JCheckBox chkEstado;
    private JButton btnSave;

    public MembresiaFormDialog(Frame owner) {
        super(owner, "Gestionar Membresías", true);
        setSize(400, 300);
        setLayout(new GridLayout(7, 2, 10, 10));
        setLocationRelativeTo(owner);

        cmbSocio = new JComboBox<>(getSocios().toArray(new Socio[0]));
        txtCantidadPases = new JTextField(20);
        txtFechaInicio = new JTextField();
        txtFechaFin = new JTextField();
        txtCosto = new JTextField(20);
        chkEstado = new JCheckBox("Activa");
        btnSave = new JButton("Guardar");

        add(new JLabel("Socio:"));
        add(cmbSocio);
        add(new JLabel("Cantidad de Pases:"));
        add(txtCantidadPases);
        add(new JLabel("Costo:"));
        add(txtCosto);
//        add(new JLabel("Fecha de Inicio:"));
//        add(txtFechaInicio);
//        add(new JLabel("Fecha de Fin:"));
//        add(txtFechaFin);
        add(new JLabel("Estado:"));
        add(chkEstado);
        add(new JLabel(""));
        add(btnSave);

        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            logicaGuardadoDeMembresia();
            }
        });
    }
    
    private void logicaGuardadoDeMembresia(){
            try {
                    Socio socio = (Socio) cmbSocio.getSelectedItem();
                    int cantidadPases = Integer.parseInt(txtCantidadPases.getText());
                    LocalDate fechaInicio = LocalDate.now();
                    LocalDate fechaFin = fechaInicio.plusDays(30*cantidadPases);
                    
                    double costo = Double.parseDouble(txtCosto.getText());
                    boolean estado = chkEstado.isSelected();

                    Membresia membresia = new Membresia(0, socio, cantidadPases, fechaInicio, fechaFin, costo, estado);
                    MembresiaData md = new MembresiaData();
                    md.agregarMembresia(membresia);
                    dispose();
                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(null, "Error al añadir la membresía: " + ex.getMessage());
JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos antes de agregar una Clase.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                }
    }

    private List<Socio> getSocios() {
        SocioData sd = new SocioData();
        List<Socio> socios = new ArrayList<>();
        
        try {
            return sd.listarSocios();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar socios: " + ex.getMessage());
            return socios;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
