/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author ramir
 */
import Data.SocioData;
import Entidades.Socio;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class SociosPanel extends JPanel {
    private JTextField txtSearch;
    private JButton btnSearch, btnAddSocio;
    private JTable table;
    private JScrollPane scrollPane;

    public SociosPanel() {
        setLayout(new BorderLayout());

        JPanel topPanel = new JPanel();
        txtSearch = new JTextField(20);
        btnSearch = new JButton("Buscar");
        btnAddSocio = new JButton("Añadir Socio");

        topPanel.add(new JLabel("Buscar:"));
        topPanel.add(txtSearch);
        topPanel.add(btnSearch);
        topPanel.add(btnAddSocio);

        add(topPanel, BorderLayout.NORTH);

        // Inicializar tabla vacía
        table = new JTable(new Object[0][0], new String[]{"ID", "DNI", "Nombre", "Apellido", "Edad", "Correo", "Teléfono", "Estado"});
        scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Action listeners
        btnSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
         busquedaPorNombre();
            }
        });

        btnAddSocio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new SocioFormDialog(null).setVisible(true);
            }
        });
    }


 void busquedaPorNombre(){
      SocioData sd = new SocioData();
                 
                try {
                    if (txtSearch.getText().isEmpty()==true){ JOptionPane.showMessageDialog(null, "El campo de texto está vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);}
                    else
                    {
                    List<Socio> socios = sd.buscarSocios(txtSearch.getText());
                    if(socios.isEmpty()){
                             JOptionPane.showMessageDialog(null, "No se encontró ningun Socio con ese nombre.");
                            return;
                        }
                    Object[][] data = new Object[socios.size()][6];
                    for (int i = 0; i < socios.size(); i++) {
                        Socio socio = socios.get(i);
                        data[i][0] = socio.getIdSocio();
                        data[i][1] = socio.getDni();
                        data[i][2] = socio.getNombre();
                        data[i][3] = socio.getApellido();
                        data[i][4] = socio.getEdad();
                        data[i][5] = socio.getCorreo();
                        data[i][6] = socio.getTelefono();
                        data[i][7] = socio.isEstado();
                        
                        
                    }
                    table.setModel(new javax.swing.table.DefaultTableModel(
                            data,
                            new String[]{"ID", "DNI", "Nombre", "Apellido", "Edad", "Correo", "Teléfono", "Estado"}
                    ));
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al buscar socios: " + ex.getMessage());
                }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
